class WPXML:
    def CreateXML_BEC(self, data):
        masterXML = """<?xml version="1.0" encoding="UTF-8" ?>
        <!-- This is a WordPress eXtended RSS file generated by WordPress as an export of your site. -->
        <!-- It contains information about your site's posts, pages, comments, categories, and other content. -->
        <!-- You may use this file to transfer that content from one site to another. -->
        <!-- This file is not intended to serve as a complete backup of your site. -->

        <!-- To import this information into a WordPress site follow these steps: -->
        <!-- 1. Log in to that site as an administrator. -->
        <!-- 2. Go to Tools: Import in the WordPress admin panel. -->
        <!-- 3. Install the "WordPress" importer from the list. -->
        <!-- 4. Activate & Run Importer. -->
        <!-- 5. Upload this file using the form provided on that page. -->
        <!-- 6. You will first be asked to map the authors in this export file to users -->
        <!--    on the site. For each author, you may choose to map to an -->
        <!--    existing user on the site or to create a new user. -->
        <!-- 7. WordPress will then import each of the posts, pages, comments, categories, etc. -->
        <!--    contained in this file into your site. -->

        <!-- generator="WordPress/4.7.3" created="2017-03-08 18:38" -->
        <rss version="2.0"
        	xmlns:excerpt="http://wordpress.org/export/1.2/excerpt/"
        	xmlns:content="http://purl.org/rss/1.0/modules/content/"
        	xmlns:wfw="http://wellformedweb.org/CommentAPI/"
        	xmlns:dc="http://purl.org/dc/elements/1.1/"
        	xmlns:wp="http://wordpress.org/export/1.2/"
        >

        <channel>
        	<title>Tracy OShaughnessy Agency</title>
        	<link>https://becaustin.wpengine.com</link>
        	<description></description>
        	<pubDate>Wed, 08 Mar 2017 18:38:34 +0000</pubDate>
        	<language>en-US</language>
        	<wp:wxr_version>1.2</wp:wxr_version>
        	<wp:base_site_url>https://becaustin.wpengine.com</wp:base_site_url>
        	<wp:base_blog_url>https://becaustin.wpengine.com</wp:base_blog_url>

        	<wp:author><wp:author_id>4</wp:author_id><wp:author_login><![CDATA[Kalai]]></wp:author_login><wp:author_email><![CDATA[kalai@tracyosh.com]]></wp:author_email><wp:author_display_name><![CDATA[Kalaiyarasan]]></wp:author_display_name><wp:author_first_name><![CDATA[Kalaiyarasan]]></wp:author_first_name><wp:author_last_name><![CDATA[]]></wp:author_last_name></wp:author>
        	<wp:author><wp:author_id>5</wp:author_id><wp:author_login><![CDATA[tmarc]]></wp:author_login><wp:author_email><![CDATA[marc@marchewitt.com]]></wp:author_email><wp:author_display_name><![CDATA[Marc Hewitt]]></wp:author_display_name><wp:author_first_name><![CDATA[Marc]]></wp:author_first_name><wp:author_last_name><![CDATA[Hewitt]]></wp:author_last_name></wp:author>


        	<generator>https://wordpress.org/?v=4.7.3</generator>"""
        # Start with opening XML

        for item in data:
            xmlItem = self.CreateItem_BEC(item)  ###Place Variable into template
            masterXML += xmlItem  ###Append to final XML

        # Finish with closing XML
        masterXML += """</channel>
        </rss>"""

        xmlFile = open('output.xml', 'w')  ###Open text file to write XML to
        # s = str(value)
        xmlFile.write(masterXML)
        xmlFile.close()

    def CreateItem_BEC(self, itemData):
        xmlItemTemplate = """<item>
    	<title><![CDATA[%(project)s]]></title>
    	<![CDATA[_wp_old_slug]]>
    	<link>https://becaustin.wpengine.com/project/%(slug)s/</link>
    	<pubDate>Wed, 08 Mar 2017 16:32:06 +0000</pubDate>
    	<dc:creator><![CDATA[tmarc]]></dc:creator>
    	<description></description>
    	<content:encoded><![CDATA[Page Content (gallery will go here)]]></content:encoded>
    	<excerpt:encoded><![CDATA[]]></excerpt:encoded>
    	<wp:post_date><![CDATA[2017-03-08 10:32:06]]></wp:post_date>
    	<wp:post_date_gmt><![CDATA[2017-03-08 16:32:06]]></wp:post_date_gmt>
    	<wp:comment_status><![CDATA[closed]]></wp:comment_status>
    	<wp:ping_status><![CDATA[closed]]></wp:ping_status>
    	<wp:post_name><![CDATA[%(slug)s]]></wp:post_name>
    	<wp:status><![CDATA[publish]]></wp:status>
    	<wp:post_parent>0</wp:post_parent>
    	<wp:menu_order>0</wp:menu_order>
    	<wp:post_type><![CDATA[project]]></wp:post_type>
    	<wp:post_password><![CDATA[]]></wp:post_password>
    	<wp:is_sticky>0</wp:is_sticky>
    	<category domain="project_category" nicename="%(category-slug)s"><![CDATA[%(category)s]]></category>
    	<wp:postmeta>
    		<wp:meta_key><![CDATA[_prlipro-post-options]]></wp:meta_key>
    		<wp:meta_value><![CDATA[a:3:{s:14:"requested_slug";s:0:"";s:19:"hide_social_buttons";b:0;s:20:"disable_replacements";b:0;}]]></wp:meta_value>
    	</wp:postmeta>
    	<wp:postmeta>
    		<wp:meta_key><![CDATA[_prlipro-post-options]]></wp:meta_key>
    		<wp:meta_value><![CDATA[a:3:{s:14:"requested_slug";s:0:"";s:19:"hide_social_buttons";b:0;s:20:"disable_replacements";b:0;}]]></wp:meta_value>
    	</wp:postmeta>
    	<wp:postmeta>
    		<wp:meta_key><![CDATA[address]]></wp:meta_key>
    		<wp:meta_value><![CDATA[%(address)s]]></wp:meta_value>
    	</wp:postmeta>
    	<wp:postmeta>
    		<wp:meta_key><![CDATA[_address]]></wp:meta_key>
    		<wp:meta_value><![CDATA[field_58c02fec768dc]]></wp:meta_value>
    	</wp:postmeta>
    	<wp:postmeta>
    		<wp:meta_key><![CDATA[size]]></wp:meta_key>
    		<wp:meta_value><![CDATA[%(size)s]]></wp:meta_value>
    	</wp:postmeta>
    	<wp:postmeta>
    		<wp:meta_key><![CDATA[_size]]></wp:meta_key>
    		<wp:meta_value><![CDATA[field_58c0301d768dd]]></wp:meta_value>
    	</wp:postmeta>
    	<wp:postmeta>
    		<wp:meta_key><![CDATA[construction_cost]]></wp:meta_key>
    		<wp:meta_value><![CDATA[%(cost)s]]></wp:meta_value>
    	</wp:postmeta>
    	<wp:postmeta>
    		<wp:meta_key><![CDATA[_construction_cost]]></wp:meta_key>
    		<wp:meta_value><![CDATA[field_58c03039768de]]></wp:meta_value>
    	</wp:postmeta>
    	<wp:postmeta>
    		<wp:meta_key><![CDATA[description]]></wp:meta_key>
    		<wp:meta_value><![CDATA[%(description)s]]></wp:meta_value>
    	</wp:postmeta>
    	<wp:postmeta>
    		<wp:meta_key><![CDATA[_description]]></wp:meta_key>
    		<wp:meta_value><![CDATA[field_58c03047768df]]></wp:meta_value>
    	</wp:postmeta>
    	<wp:postmeta>
    		<wp:meta_key><![CDATA[owner]]></wp:meta_key>
    		<wp:meta_value><![CDATA[%(owner)s]]></wp:meta_value>
    	</wp:postmeta>
    	<wp:postmeta>
    		<wp:meta_key><![CDATA[_owner]]></wp:meta_key>
    		<wp:meta_value><![CDATA[field_58c03052768e0]]></wp:meta_value>
    	</wp:postmeta>
    	<wp:postmeta>
    		<wp:meta_key><![CDATA[architect]]></wp:meta_key>
    		<wp:meta_value><![CDATA[%(architect)s]]></wp:meta_value>
    	</wp:postmeta>
    	<wp:postmeta>
    		<wp:meta_key><![CDATA[_architect]]></wp:meta_key>
    		<wp:meta_value><![CDATA[field_58c03063768e1]]></wp:meta_value>
    	</wp:postmeta>
    	<wp:postmeta>
    		<wp:meta_key><![CDATA[architect_website]]></wp:meta_key>
    		<wp:meta_value><![CDATA[%(architectWebsite)s]]></wp:meta_value>
    	</wp:postmeta>
    	<wp:postmeta>
    		<wp:meta_key><![CDATA[_architect_website]]></wp:meta_key>
    		<wp:meta_value><![CDATA[field_58c03071768e2]]></wp:meta_value>
    	</wp:postmeta>
    	<wp:postmeta>
    		<wp:meta_key><![CDATA[_edit_last]]></wp:meta_key>
    		<wp:meta_value><![CDATA[5]]></wp:meta_value>
    	</wp:postmeta>
    	<wp:postmeta>
    		<wp:meta_key><![CDATA[_wp_old_slug]]></wp:meta_key>
    		<wp:meta_value><![CDATA[test-slug]]></wp:meta_value>
    	</wp:postmeta>
    </item>
    """
        # print( xmlItemTemplate%itemData )
        return xmlItemTemplate % itemData
